#!/usr/bin/env python3
#
# Script to download all attachments list of jira tickets
#

import sys
import os
sys.path.append(os.path.join(os.getenv('HOME'), 'bin'))
from jira import JIRA
from genericlib import setup_cache, cache

def get_issue(issue):
    options = { 'server': cache['server'] }
    cli = JIRA(options, basic_auth=(cache['username'], cache['password']))
    return cli.issue(issue)

if __name__ == '__main__':
    if len(sys.argv) <= 1:
        print('usage: <ticket-id>')
        sys.exit(1)

    issues = map(get_issue, sys.argv[1:])
    for issue in issues:
        print('{}: {}'.format(issue, issue.fields.summary))
        if os.path.exists('{}'.format(issue)):
            print('error: {} already exists'.format(issue))
            sys.exit(1)
        os.mkdir(str(issue))
        if len(issue.fields.attachment) == 0:
            print('No attachments for {}'.format(issue))
            sys.exit(1)
        for attachment in issue.fields.attachment:
            print(' -- fetching {}'.format(attachment))
            with open(os.path.join('{}/{}'.format(issue, attachment)), 'wb+') as f:
                f.write(attachment.get())

