#!/usr/bin/env python3
#
# Script to list open/in progrss tickets assigned to me
#

import sys

import os
sys.path.append(os.path.join(os.getenv('HOME'), 'bin'))

from jira import JIRA

from genericlib import setup_cache, cache

def get_my_issues():
    global cache

    options = { 'server': cache['server'] }
    cli = JIRA(options, basic_auth=(cache['username'], cache['password']))

    jql = 'assignee = currentuser() and status ' \
          'not in ("Closed", "Resolved")'
    return cli.search_issues(jql)

GREEN = '\033[92m'
RED = '\033[91m'
ENDC = '\033[0m'

if __name__ == '__main__':
    for issue in get_my_issues():
        print('{}{}{}: {}\n - {}/browse/{} [{}{}{}]'.format(RED,
                                            issue,
                                            ENDC,
                                            issue.fields.summary,
                                            cache['server'],
                                            issue, 
                                            GREEN,    
                                            issue.fields.status,
                                            ENDC))
